### ISSUE TITLE
Web UI doesnt display result?

### ISSUE THREAD

**Issue by NOV-DM** [socialpandas/sidekiq_monitor#10]
In the list view I can't see the result:
![image](https://f.cloud.github.com/assets/3205115/1130240/785e8f52-1ba1-11e3-81ea-92edb68f1cc8.png)
but when i click on details I can see it there:
![image](https://f.cloud.github.com/assets/3205115/1130242/88d2806e-1ba1-11e3-9166-0d92335039d5.png)

**Comment by tombenner** [comment]
You'll need to set a `:message` key in your result hash (see [the newly-updated README](https://github.com/socialpandas/sidekiq_monitor#setting-a-job-result) for details), and that will be shown in the jobs table above. (Because there isn't space to showing a stringified JSON object in that cell, it made sense to only show a specified string there.) Sorry for lack of clarity, this hadn't been previously documented, but it is now.
