### ISSUE TITLE
superclass must be a Class

### ISSUE THREAD

**Issue by 45sound** [socialpandas/sidekiq_monitor#22]
When I run 
rails g sidekiq:monitor:install
I get 
/sidekiq_monitor-0.1.2/app/datatables/sidekiq/monitor/jobs_datatable.rb:3:in `<module:Monitor>': superclass must be a Class (Module given) (TypeError)
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq_monitor-0.1.2/app/datatables/sidekiq/monitor/jobs_datatable.rb:2:in`module:Sidekiq'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq_monitor-0.1.2/app/datatables/sidekiq/monitor/jobs_datatable.rb:1:in `<top (required)>'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in`require'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `block in require'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in`load_dependency'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'

on Rails 4.0.5, sidekiq 2.17.7, sidekiq_monitor (0.1.2). 

Tried on sidekiq 3 also, same error
Can't get past this.
Vinny

**Comment by tombenner** [comment]
This is due to a backward incompatible change that was introduced in version 0.1.0 of [ajax-datatables-rails](https://github.com/antillas21/ajax-datatables-rails). It looks like ajax-datatables-rails is seeing new development now, so to avoid any other breaking changes, I've replaced ajax-datatables-rails with [rails-datatables](https://github.com/tombenner/rails-datatables) (my fork of ajax-datatables-rails, which includes other benefits, too). If ajax-datatables-rails continues to be improved, we might consider switching back to it at some point.

This fix is included in 0.1.3, which is now available. Thanks for catching this!
